# fly.toml app configuration file generated for api-django-portafolio-red-surf-4814 on 2025-06-27T10:11:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-django-portafolio-red-surf-4814'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'sh -c "python manage.py migrate"'

[env]
  ALLOWED_HOSTS = '*'
  DEBUG = 'False'
  DJANGO_SETTINGS_MODULE = 'apiportafolio.settings'
  PORT = '8000'
  PYTHONPATH = '/app'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15ms'
    timeout = '2ms'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
